FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /matcher ./agents/matcher

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /matcher .
COPY --from=builder /app/internal ./internal
COPY --from=builder /app/go.mod .

ENV ENABLE_LOGGING=true

CMD ["./matcher"]
